# Generated by Django 2.2.6 on 2019-11-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('sub_catagory', models.CharField(default='', max_length=120)),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('price', models.CharField(default='', max_length=120)),
                ('discount', models.CharField(default='', max_length=120)),
                ('about', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=0)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('name', models.CharField(default='', max_length=120)),
                ('address', models.TextField(default='')),
                ('pin', models.CharField(default='', max_length=120)),
                ('mobile_number', models.CharField(default='', max_length=120)),
                ('state', models.CharField(default='West Bengal', max_length=120)),
                ('cart_item_quantity', models.IntegerField(default=0)),
                ('cart_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ItemsModel')),
            ],
        ),
    ]
