# Generated by Django 2.2.6 on 2019-11-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_catagory_sub_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='sub_catagory',
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Catagory'),
        ),
    ]
