# Generated by Django 2.2.6 on 2019-11-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191123_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery_type',
            name='Fixed',
            field=models.BooleanField(default=False),
        ),
    ]
