# Generated by Django 2.2.3 on 2019-11-26 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_battery_type_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='woner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermodel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='battery_capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Battery_capacity'),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='battery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Battery_type'),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Catagory'),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='name',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='os_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Os_name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cart_item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ItemsModel'),
        ),
    ]
