# Generated by Django 2.2.3 on 2019-11-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191126_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cart_item_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
